# Generated by Django 4.2.30 on 2026-09-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acopiador',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('acopiador', 'Acopiador')], default='acopiador', max_length=20),
        ),
    ]
