# Generated by Django 4.2.30 on 2026-09-11 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoProductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_seguimiento', models.DateTimeField(auto_now_add=True)),
                ('tipo_seguimiento', models.CharField(choices=[('visita', 'Visita'), ('llamada', 'Llamada'), ('negociacion', 'Negociación'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('estado_productor', models.CharField(blank=True, max_length=100)),
                ('interes_venta', models.CharField(choices=[('alto', 'Alto'), ('medio', 'Medio'), ('bajo', 'Bajo'), ('ninguno', 'Ninguno')], default='ninguno', max_length=20)),
                ('proxima_accion', models.TextField(blank=True)),
                ('observacion', models.TextField(blank=True)),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='productores.productor')),
            ],
            options={
                'db_table': 'seguimiento_productor',
                'ordering': ['-fecha_seguimiento'],
            },
        ),
    ]
