# Generated by Django 4.2.30 on 2026-09-11 17:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=15, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('comunidad', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('padron', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productores', to='catalogos.padron')),
            ],
            options={
                'db_table': 'productor',
            },
        ),
        migrations.CreateModel(
            name='Geocerca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('parcela', 'Parcela'), ('area_acopio', 'Área de acopio'), ('otro', 'Otro')], default='parcela', max_length=20)),
                ('geometria', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geocercas', to='productores.productor')),
            ],
            options={
                'verbose_name_plural': 'geocercas',
                'db_table': 'geocerca',
            },
        ),
    ]
